### PR TITLE
Add tests for fraud

### PR DESCRIPTION
**Pull request by camelmasa**
I added tests for fraud check.

@k2nr Please review if you have time :watch:

### CODE REVIEW

**Comment by k2nr** [comment]
@camelmasa LGTM :+1: do these tests pass?

**Comment by camelmasa** [comment]
r

**Comment by camelmasa** [comment]
@k2nr Yes, I passed tests :smiley:

**Comment by k2nr** [comment]
@camelmasa great thanks! I'll cherry-pick and squash into the PR-ed branch

**Comment by k2nr** [comment]
done. closing this

**Comment by camelmasa** [comment]
@k2nr Thank you for reviewing :clap:

**Pull request closed without merging**
